package com.lym.pojo;

import java.util.Date;

public class WeixinCommand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.cmdName
     *
     * @mbggenerated
     */
    private String cmdname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.cmdType
     *
     * @mbggenerated
     */
    private String cmdtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.cmdContent
     *
     * @mbggenerated
     */
    private String cmdcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.cmdnum
     *
     * @mbggenerated
     */
    private Integer cmdnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle1
     *
     * @mbggenerated
     */
    private String imgtitle1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl1
     *
     * @mbggenerated
     */
    private String imgurl1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink1
     *
     * @mbggenerated
     */
    private String imglink1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes1
     *
     * @mbggenerated
     */
    private String imgdes1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle2
     *
     * @mbggenerated
     */
    private String imgtitle2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl2
     *
     * @mbggenerated
     */
    private String imgurl2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink2
     *
     * @mbggenerated
     */
    private String imglink2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes2
     *
     * @mbggenerated
     */
    private String imgdes2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle3
     *
     * @mbggenerated
     */
    private String imgtitle3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl3
     *
     * @mbggenerated
     */
    private String imgurl3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink3
     *
     * @mbggenerated
     */
    private String imglink3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes3
     *
     * @mbggenerated
     */
    private String imgdes3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle4
     *
     * @mbggenerated
     */
    private String imgtitle4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl4
     *
     * @mbggenerated
     */
    private String imgurl4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink4
     *
     * @mbggenerated
     */
    private String imglink4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes4
     *
     * @mbggenerated
     */
    private String imgdes4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle5
     *
     * @mbggenerated
     */
    private String imgtitle5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl5
     *
     * @mbggenerated
     */
    private String imgurl5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink5
     *
     * @mbggenerated
     */
    private String imglink5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes5
     *
     * @mbggenerated
     */
    private String imgdes5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle6
     *
     * @mbggenerated
     */
    private String imgtitle6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl6
     *
     * @mbggenerated
     */
    private String imgurl6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink6
     *
     * @mbggenerated
     */
    private String imglink6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes6
     *
     * @mbggenerated
     */
    private String imgdes6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle7
     *
     * @mbggenerated
     */
    private String imgtitle7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl7
     *
     * @mbggenerated
     */
    private String imgurl7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink7
     *
     * @mbggenerated
     */
    private String imglink7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes7
     *
     * @mbggenerated
     */
    private String imgdes7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle8
     *
     * @mbggenerated
     */
    private String imgtitle8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl8
     *
     * @mbggenerated
     */
    private String imgurl8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink8
     *
     * @mbggenerated
     */
    private String imglink8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes8
     *
     * @mbggenerated
     */
    private String imgdes8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle9
     *
     * @mbggenerated
     */
    private String imgtitle9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl9
     *
     * @mbggenerated
     */
    private String imgurl9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink9
     *
     * @mbggenerated
     */
    private String imglink9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes9
     *
     * @mbggenerated
     */
    private String imgdes9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgtitle10
     *
     * @mbggenerated
     */
    private String imgtitle10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgurl10
     *
     * @mbggenerated
     */
    private String imgurl10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imglink10
     *
     * @mbggenerated
     */
    private String imglink10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.Imgdes10
     *
     * @mbggenerated
     */
    private String imgdes10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.audiotitle
     *
     * @mbggenerated
     */
    private String audiotitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.audiourl
     *
     * @mbggenerated
     */
    private String audiourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.audioHQurl
     *
     * @mbggenerated
     */
    private String audiohqurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.audiodes
     *
     * @mbggenerated
     */
    private String audiodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.audiotxt
     *
     * @mbggenerated
     */
    private String audiotxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_command.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.cmdName
     *
     * @return the value of tb_weixin_command.cmdName
     *
     * @mbggenerated
     */
    public String getCmdname() {
        return cmdname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.cmdName
     *
     * @param cmdname the value for tb_weixin_command.cmdName
     *
     * @mbggenerated
     */
    public void setCmdname(String cmdname) {
        this.cmdname = cmdname == null ? null : cmdname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.cmdType
     *
     * @return the value of tb_weixin_command.cmdType
     *
     * @mbggenerated
     */
    public String getCmdtype() {
        return cmdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.cmdType
     *
     * @param cmdtype the value for tb_weixin_command.cmdType
     *
     * @mbggenerated
     */
    public void setCmdtype(String cmdtype) {
        this.cmdtype = cmdtype == null ? null : cmdtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.cmdContent
     *
     * @return the value of tb_weixin_command.cmdContent
     *
     * @mbggenerated
     */
    public String getCmdcontent() {
        return cmdcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.cmdContent
     *
     * @param cmdcontent the value for tb_weixin_command.cmdContent
     *
     * @mbggenerated
     */
    public void setCmdcontent(String cmdcontent) {
        this.cmdcontent = cmdcontent == null ? null : cmdcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.cmdnum
     *
     * @return the value of tb_weixin_command.cmdnum
     *
     * @mbggenerated
     */
    public Integer getCmdnum() {
        return cmdnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.cmdnum
     *
     * @param cmdnum the value for tb_weixin_command.cmdnum
     *
     * @mbggenerated
     */
    public void setCmdnum(Integer cmdnum) {
        this.cmdnum = cmdnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle1
     *
     * @return the value of tb_weixin_command.Imgtitle1
     *
     * @mbggenerated
     */
    public String getImgtitle1() {
        return imgtitle1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle1
     *
     * @param imgtitle1 the value for tb_weixin_command.Imgtitle1
     *
     * @mbggenerated
     */
    public void setImgtitle1(String imgtitle1) {
        this.imgtitle1 = imgtitle1 == null ? null : imgtitle1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl1
     *
     * @return the value of tb_weixin_command.Imgurl1
     *
     * @mbggenerated
     */
    public String getImgurl1() {
        return imgurl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl1
     *
     * @param imgurl1 the value for tb_weixin_command.Imgurl1
     *
     * @mbggenerated
     */
    public void setImgurl1(String imgurl1) {
        this.imgurl1 = imgurl1 == null ? null : imgurl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink1
     *
     * @return the value of tb_weixin_command.Imglink1
     *
     * @mbggenerated
     */
    public String getImglink1() {
        return imglink1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink1
     *
     * @param imglink1 the value for tb_weixin_command.Imglink1
     *
     * @mbggenerated
     */
    public void setImglink1(String imglink1) {
        this.imglink1 = imglink1 == null ? null : imglink1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes1
     *
     * @return the value of tb_weixin_command.Imgdes1
     *
     * @mbggenerated
     */
    public String getImgdes1() {
        return imgdes1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes1
     *
     * @param imgdes1 the value for tb_weixin_command.Imgdes1
     *
     * @mbggenerated
     */
    public void setImgdes1(String imgdes1) {
        this.imgdes1 = imgdes1 == null ? null : imgdes1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle2
     *
     * @return the value of tb_weixin_command.Imgtitle2
     *
     * @mbggenerated
     */
    public String getImgtitle2() {
        return imgtitle2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle2
     *
     * @param imgtitle2 the value for tb_weixin_command.Imgtitle2
     *
     * @mbggenerated
     */
    public void setImgtitle2(String imgtitle2) {
        this.imgtitle2 = imgtitle2 == null ? null : imgtitle2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl2
     *
     * @return the value of tb_weixin_command.Imgurl2
     *
     * @mbggenerated
     */
    public String getImgurl2() {
        return imgurl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl2
     *
     * @param imgurl2 the value for tb_weixin_command.Imgurl2
     *
     * @mbggenerated
     */
    public void setImgurl2(String imgurl2) {
        this.imgurl2 = imgurl2 == null ? null : imgurl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink2
     *
     * @return the value of tb_weixin_command.Imglink2
     *
     * @mbggenerated
     */
    public String getImglink2() {
        return imglink2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink2
     *
     * @param imglink2 the value for tb_weixin_command.Imglink2
     *
     * @mbggenerated
     */
    public void setImglink2(String imglink2) {
        this.imglink2 = imglink2 == null ? null : imglink2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes2
     *
     * @return the value of tb_weixin_command.Imgdes2
     *
     * @mbggenerated
     */
    public String getImgdes2() {
        return imgdes2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes2
     *
     * @param imgdes2 the value for tb_weixin_command.Imgdes2
     *
     * @mbggenerated
     */
    public void setImgdes2(String imgdes2) {
        this.imgdes2 = imgdes2 == null ? null : imgdes2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle3
     *
     * @return the value of tb_weixin_command.Imgtitle3
     *
     * @mbggenerated
     */
    public String getImgtitle3() {
        return imgtitle3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle3
     *
     * @param imgtitle3 the value for tb_weixin_command.Imgtitle3
     *
     * @mbggenerated
     */
    public void setImgtitle3(String imgtitle3) {
        this.imgtitle3 = imgtitle3 == null ? null : imgtitle3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl3
     *
     * @return the value of tb_weixin_command.Imgurl3
     *
     * @mbggenerated
     */
    public String getImgurl3() {
        return imgurl3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl3
     *
     * @param imgurl3 the value for tb_weixin_command.Imgurl3
     *
     * @mbggenerated
     */
    public void setImgurl3(String imgurl3) {
        this.imgurl3 = imgurl3 == null ? null : imgurl3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink3
     *
     * @return the value of tb_weixin_command.Imglink3
     *
     * @mbggenerated
     */
    public String getImglink3() {
        return imglink3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink3
     *
     * @param imglink3 the value for tb_weixin_command.Imglink3
     *
     * @mbggenerated
     */
    public void setImglink3(String imglink3) {
        this.imglink3 = imglink3 == null ? null : imglink3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes3
     *
     * @return the value of tb_weixin_command.Imgdes3
     *
     * @mbggenerated
     */
    public String getImgdes3() {
        return imgdes3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes3
     *
     * @param imgdes3 the value for tb_weixin_command.Imgdes3
     *
     * @mbggenerated
     */
    public void setImgdes3(String imgdes3) {
        this.imgdes3 = imgdes3 == null ? null : imgdes3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle4
     *
     * @return the value of tb_weixin_command.Imgtitle4
     *
     * @mbggenerated
     */
    public String getImgtitle4() {
        return imgtitle4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle4
     *
     * @param imgtitle4 the value for tb_weixin_command.Imgtitle4
     *
     * @mbggenerated
     */
    public void setImgtitle4(String imgtitle4) {
        this.imgtitle4 = imgtitle4 == null ? null : imgtitle4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl4
     *
     * @return the value of tb_weixin_command.Imgurl4
     *
     * @mbggenerated
     */
    public String getImgurl4() {
        return imgurl4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl4
     *
     * @param imgurl4 the value for tb_weixin_command.Imgurl4
     *
     * @mbggenerated
     */
    public void setImgurl4(String imgurl4) {
        this.imgurl4 = imgurl4 == null ? null : imgurl4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink4
     *
     * @return the value of tb_weixin_command.Imglink4
     *
     * @mbggenerated
     */
    public String getImglink4() {
        return imglink4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink4
     *
     * @param imglink4 the value for tb_weixin_command.Imglink4
     *
     * @mbggenerated
     */
    public void setImglink4(String imglink4) {
        this.imglink4 = imglink4 == null ? null : imglink4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes4
     *
     * @return the value of tb_weixin_command.Imgdes4
     *
     * @mbggenerated
     */
    public String getImgdes4() {
        return imgdes4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes4
     *
     * @param imgdes4 the value for tb_weixin_command.Imgdes4
     *
     * @mbggenerated
     */
    public void setImgdes4(String imgdes4) {
        this.imgdes4 = imgdes4 == null ? null : imgdes4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle5
     *
     * @return the value of tb_weixin_command.Imgtitle5
     *
     * @mbggenerated
     */
    public String getImgtitle5() {
        return imgtitle5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle5
     *
     * @param imgtitle5 the value for tb_weixin_command.Imgtitle5
     *
     * @mbggenerated
     */
    public void setImgtitle5(String imgtitle5) {
        this.imgtitle5 = imgtitle5 == null ? null : imgtitle5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl5
     *
     * @return the value of tb_weixin_command.Imgurl5
     *
     * @mbggenerated
     */
    public String getImgurl5() {
        return imgurl5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl5
     *
     * @param imgurl5 the value for tb_weixin_command.Imgurl5
     *
     * @mbggenerated
     */
    public void setImgurl5(String imgurl5) {
        this.imgurl5 = imgurl5 == null ? null : imgurl5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink5
     *
     * @return the value of tb_weixin_command.Imglink5
     *
     * @mbggenerated
     */
    public String getImglink5() {
        return imglink5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink5
     *
     * @param imglink5 the value for tb_weixin_command.Imglink5
     *
     * @mbggenerated
     */
    public void setImglink5(String imglink5) {
        this.imglink5 = imglink5 == null ? null : imglink5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes5
     *
     * @return the value of tb_weixin_command.Imgdes5
     *
     * @mbggenerated
     */
    public String getImgdes5() {
        return imgdes5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes5
     *
     * @param imgdes5 the value for tb_weixin_command.Imgdes5
     *
     * @mbggenerated
     */
    public void setImgdes5(String imgdes5) {
        this.imgdes5 = imgdes5 == null ? null : imgdes5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle6
     *
     * @return the value of tb_weixin_command.Imgtitle6
     *
     * @mbggenerated
     */
    public String getImgtitle6() {
        return imgtitle6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle6
     *
     * @param imgtitle6 the value for tb_weixin_command.Imgtitle6
     *
     * @mbggenerated
     */
    public void setImgtitle6(String imgtitle6) {
        this.imgtitle6 = imgtitle6 == null ? null : imgtitle6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl6
     *
     * @return the value of tb_weixin_command.Imgurl6
     *
     * @mbggenerated
     */
    public String getImgurl6() {
        return imgurl6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl6
     *
     * @param imgurl6 the value for tb_weixin_command.Imgurl6
     *
     * @mbggenerated
     */
    public void setImgurl6(String imgurl6) {
        this.imgurl6 = imgurl6 == null ? null : imgurl6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink6
     *
     * @return the value of tb_weixin_command.Imglink6
     *
     * @mbggenerated
     */
    public String getImglink6() {
        return imglink6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink6
     *
     * @param imglink6 the value for tb_weixin_command.Imglink6
     *
     * @mbggenerated
     */
    public void setImglink6(String imglink6) {
        this.imglink6 = imglink6 == null ? null : imglink6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes6
     *
     * @return the value of tb_weixin_command.Imgdes6
     *
     * @mbggenerated
     */
    public String getImgdes6() {
        return imgdes6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes6
     *
     * @param imgdes6 the value for tb_weixin_command.Imgdes6
     *
     * @mbggenerated
     */
    public void setImgdes6(String imgdes6) {
        this.imgdes6 = imgdes6 == null ? null : imgdes6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle7
     *
     * @return the value of tb_weixin_command.Imgtitle7
     *
     * @mbggenerated
     */
    public String getImgtitle7() {
        return imgtitle7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle7
     *
     * @param imgtitle7 the value for tb_weixin_command.Imgtitle7
     *
     * @mbggenerated
     */
    public void setImgtitle7(String imgtitle7) {
        this.imgtitle7 = imgtitle7 == null ? null : imgtitle7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl7
     *
     * @return the value of tb_weixin_command.Imgurl7
     *
     * @mbggenerated
     */
    public String getImgurl7() {
        return imgurl7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl7
     *
     * @param imgurl7 the value for tb_weixin_command.Imgurl7
     *
     * @mbggenerated
     */
    public void setImgurl7(String imgurl7) {
        this.imgurl7 = imgurl7 == null ? null : imgurl7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink7
     *
     * @return the value of tb_weixin_command.Imglink7
     *
     * @mbggenerated
     */
    public String getImglink7() {
        return imglink7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink7
     *
     * @param imglink7 the value for tb_weixin_command.Imglink7
     *
     * @mbggenerated
     */
    public void setImglink7(String imglink7) {
        this.imglink7 = imglink7 == null ? null : imglink7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes7
     *
     * @return the value of tb_weixin_command.Imgdes7
     *
     * @mbggenerated
     */
    public String getImgdes7() {
        return imgdes7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes7
     *
     * @param imgdes7 the value for tb_weixin_command.Imgdes7
     *
     * @mbggenerated
     */
    public void setImgdes7(String imgdes7) {
        this.imgdes7 = imgdes7 == null ? null : imgdes7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle8
     *
     * @return the value of tb_weixin_command.Imgtitle8
     *
     * @mbggenerated
     */
    public String getImgtitle8() {
        return imgtitle8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle8
     *
     * @param imgtitle8 the value for tb_weixin_command.Imgtitle8
     *
     * @mbggenerated
     */
    public void setImgtitle8(String imgtitle8) {
        this.imgtitle8 = imgtitle8 == null ? null : imgtitle8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl8
     *
     * @return the value of tb_weixin_command.Imgurl8
     *
     * @mbggenerated
     */
    public String getImgurl8() {
        return imgurl8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl8
     *
     * @param imgurl8 the value for tb_weixin_command.Imgurl8
     *
     * @mbggenerated
     */
    public void setImgurl8(String imgurl8) {
        this.imgurl8 = imgurl8 == null ? null : imgurl8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink8
     *
     * @return the value of tb_weixin_command.Imglink8
     *
     * @mbggenerated
     */
    public String getImglink8() {
        return imglink8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink8
     *
     * @param imglink8 the value for tb_weixin_command.Imglink8
     *
     * @mbggenerated
     */
    public void setImglink8(String imglink8) {
        this.imglink8 = imglink8 == null ? null : imglink8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes8
     *
     * @return the value of tb_weixin_command.Imgdes8
     *
     * @mbggenerated
     */
    public String getImgdes8() {
        return imgdes8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes8
     *
     * @param imgdes8 the value for tb_weixin_command.Imgdes8
     *
     * @mbggenerated
     */
    public void setImgdes8(String imgdes8) {
        this.imgdes8 = imgdes8 == null ? null : imgdes8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle9
     *
     * @return the value of tb_weixin_command.Imgtitle9
     *
     * @mbggenerated
     */
    public String getImgtitle9() {
        return imgtitle9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle9
     *
     * @param imgtitle9 the value for tb_weixin_command.Imgtitle9
     *
     * @mbggenerated
     */
    public void setImgtitle9(String imgtitle9) {
        this.imgtitle9 = imgtitle9 == null ? null : imgtitle9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl9
     *
     * @return the value of tb_weixin_command.Imgurl9
     *
     * @mbggenerated
     */
    public String getImgurl9() {
        return imgurl9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl9
     *
     * @param imgurl9 the value for tb_weixin_command.Imgurl9
     *
     * @mbggenerated
     */
    public void setImgurl9(String imgurl9) {
        this.imgurl9 = imgurl9 == null ? null : imgurl9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink9
     *
     * @return the value of tb_weixin_command.Imglink9
     *
     * @mbggenerated
     */
    public String getImglink9() {
        return imglink9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink9
     *
     * @param imglink9 the value for tb_weixin_command.Imglink9
     *
     * @mbggenerated
     */
    public void setImglink9(String imglink9) {
        this.imglink9 = imglink9 == null ? null : imglink9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes9
     *
     * @return the value of tb_weixin_command.Imgdes9
     *
     * @mbggenerated
     */
    public String getImgdes9() {
        return imgdes9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes9
     *
     * @param imgdes9 the value for tb_weixin_command.Imgdes9
     *
     * @mbggenerated
     */
    public void setImgdes9(String imgdes9) {
        this.imgdes9 = imgdes9 == null ? null : imgdes9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgtitle10
     *
     * @return the value of tb_weixin_command.Imgtitle10
     *
     * @mbggenerated
     */
    public String getImgtitle10() {
        return imgtitle10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgtitle10
     *
     * @param imgtitle10 the value for tb_weixin_command.Imgtitle10
     *
     * @mbggenerated
     */
    public void setImgtitle10(String imgtitle10) {
        this.imgtitle10 = imgtitle10 == null ? null : imgtitle10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgurl10
     *
     * @return the value of tb_weixin_command.Imgurl10
     *
     * @mbggenerated
     */
    public String getImgurl10() {
        return imgurl10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgurl10
     *
     * @param imgurl10 the value for tb_weixin_command.Imgurl10
     *
     * @mbggenerated
     */
    public void setImgurl10(String imgurl10) {
        this.imgurl10 = imgurl10 == null ? null : imgurl10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imglink10
     *
     * @return the value of tb_weixin_command.Imglink10
     *
     * @mbggenerated
     */
    public String getImglink10() {
        return imglink10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imglink10
     *
     * @param imglink10 the value for tb_weixin_command.Imglink10
     *
     * @mbggenerated
     */
    public void setImglink10(String imglink10) {
        this.imglink10 = imglink10 == null ? null : imglink10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.Imgdes10
     *
     * @return the value of tb_weixin_command.Imgdes10
     *
     * @mbggenerated
     */
    public String getImgdes10() {
        return imgdes10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.Imgdes10
     *
     * @param imgdes10 the value for tb_weixin_command.Imgdes10
     *
     * @mbggenerated
     */
    public void setImgdes10(String imgdes10) {
        this.imgdes10 = imgdes10 == null ? null : imgdes10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.audiotitle
     *
     * @return the value of tb_weixin_command.audiotitle
     *
     * @mbggenerated
     */
    public String getAudiotitle() {
        return audiotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.audiotitle
     *
     * @param audiotitle the value for tb_weixin_command.audiotitle
     *
     * @mbggenerated
     */
    public void setAudiotitle(String audiotitle) {
        this.audiotitle = audiotitle == null ? null : audiotitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.audiourl
     *
     * @return the value of tb_weixin_command.audiourl
     *
     * @mbggenerated
     */
    public String getAudiourl() {
        return audiourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.audiourl
     *
     * @param audiourl the value for tb_weixin_command.audiourl
     *
     * @mbggenerated
     */
    public void setAudiourl(String audiourl) {
        this.audiourl = audiourl == null ? null : audiourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.audioHQurl
     *
     * @return the value of tb_weixin_command.audioHQurl
     *
     * @mbggenerated
     */
    public String getAudiohqurl() {
        return audiohqurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.audioHQurl
     *
     * @param audiohqurl the value for tb_weixin_command.audioHQurl
     *
     * @mbggenerated
     */
    public void setAudiohqurl(String audiohqurl) {
        this.audiohqurl = audiohqurl == null ? null : audiohqurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.audiodes
     *
     * @return the value of tb_weixin_command.audiodes
     *
     * @mbggenerated
     */
    public String getAudiodes() {
        return audiodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.audiodes
     *
     * @param audiodes the value for tb_weixin_command.audiodes
     *
     * @mbggenerated
     */
    public void setAudiodes(String audiodes) {
        this.audiodes = audiodes == null ? null : audiodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.audiotxt
     *
     * @return the value of tb_weixin_command.audiotxt
     *
     * @mbggenerated
     */
    public String getAudiotxt() {
        return audiotxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.audiotxt
     *
     * @param audiotxt the value for tb_weixin_command.audiotxt
     *
     * @mbggenerated
     */
    public void setAudiotxt(String audiotxt) {
        this.audiotxt = audiotxt == null ? null : audiotxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.begin_time
     *
     * @return the value of tb_weixin_command.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.begin_time
     *
     * @param beginTime the value for tb_weixin_command.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.end_time
     *
     * @return the value of tb_weixin_command.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.end_time
     *
     * @param endTime the value for tb_weixin_command.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.type
     *
     * @return the value of tb_weixin_command.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.type
     *
     * @param type the value for tb_weixin_command.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_command.update_time
     *
     * @return the value of tb_weixin_command.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_command.update_time
     *
     * @param updateTime the value for tb_weixin_command.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}