package com.lym.pojo;

public class WeixinMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.cmdkey
     *
     * @mbggenerated
     */
    private String cmdkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.level
     *
     * @mbggenerated
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_weixin_menu.parent
     *
     * @mbggenerated
     */
    private Integer parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.ID
     *
     * @return the value of tb_weixin_menu.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.ID
     *
     * @param id the value for tb_weixin_menu.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.name
     *
     * @return the value of tb_weixin_menu.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.name
     *
     * @param name the value for tb_weixin_menu.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.cmdkey
     *
     * @return the value of tb_weixin_menu.cmdkey
     *
     * @mbggenerated
     */
    public String getCmdkey() {
        return cmdkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.cmdkey
     *
     * @param cmdkey the value for tb_weixin_menu.cmdkey
     *
     * @mbggenerated
     */
    public void setCmdkey(String cmdkey) {
        this.cmdkey = cmdkey == null ? null : cmdkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.type
     *
     * @return the value of tb_weixin_menu.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.type
     *
     * @param type the value for tb_weixin_menu.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.url
     *
     * @return the value of tb_weixin_menu.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.url
     *
     * @param url the value for tb_weixin_menu.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.level
     *
     * @return the value of tb_weixin_menu.level
     *
     * @mbggenerated
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.level
     *
     * @param level the value for tb_weixin_menu.level
     *
     * @mbggenerated
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_weixin_menu.parent
     *
     * @return the value of tb_weixin_menu.parent
     *
     * @mbggenerated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_weixin_menu.parent
     *
     * @param parent the value for tb_weixin_menu.parent
     *
     * @mbggenerated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}