package com.lym.pojo.mapper;

import com.lym.pojo.WeixinCommand;
import com.lym.pojo.WeixinCommandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinCommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int countByExample(WeixinCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cmdname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int insert(WeixinCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int insertSelective(WeixinCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    List<WeixinCommand> selectByExample(WeixinCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    WeixinCommand selectByPrimaryKey(String cmdname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinCommand record, @Param("example") WeixinCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinCommand record, @Param("example") WeixinCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_command
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinCommand record);
}