package com.lym.pojo.mapper;

import com.lym.pojo.WeixinNews;
import com.lym.pojo.WeixinNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixinNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int countByExample(WeixinNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int insert(WeixinNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int insertSelective(WeixinNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    List<WeixinNews> selectByExample(WeixinNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    WeixinNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinNews record, @Param("example") WeixinNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinNews record, @Param("example") WeixinNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_weixin_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinNews record);
}